//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdClubFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public Clan()
        {
            this.Iznajmljivanjes = new HashSet<Iznajmljivanje>();
        }
    
        public int ClanID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Adresa { get; set; }
        public string Telefon { get; set; }
        public string JMBG { get; set; }

        public string PunoIme
        {
            get
            {
                return Ime + " " + Prezime;
            }
        }
    
        public virtual ICollection<Iznajmljivanje> Iznajmljivanjes { get; set; }
    }
}
