//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdClubFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DvdKlubEntities : DbContext
    {
        public DvdKlubEntities()
            : base("name=DvdKlubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Clan> Clans { get; set; }
        public DbSet<Film> Films { get; set; }
        public DbSet<Iznajmljivanje> Iznajmljivanjes { get; set; }
    }
}
