//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DvdClubFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public Film()
        {
            this.Iznajmljivanjes = new HashSet<Iznajmljivanje>();
        }
    
        public int FilmID { get; set; }
        public string NazivFilma { get; set; }
        public string Zanr { get; set; }
        public string Trajanje { get; set; }
    
        public virtual ICollection<Iznajmljivanje> Iznajmljivanjes { get; set; }
    }
}
